### ISSUE TITLE
sapbtp-operator vs. sap-btp-operator

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/btp-service-manager#4]
### Issue description

Hello,

the documentation in Step 3: "Deploy the SAP BTP service operator in the cluster using the obtained access credentials." uses sapbtp-operator and the example in Step 4 sap-btp-operator. I would suggest to align the steps with [Setup Step 4](https://github.com/SAP/sap-btp-service-operator?tab=readme-ov-file#setup).

Best Regards
Gregor

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Setup

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/service-manager/sap-service-manager/setup

**Comment by danielforsap** [comment]
Hi,
I will add the link to the relevant public GitHub documentation (https://github.com/SAP/sap-btp-service-operator/blob/main/README.md) and remove the content here.
