### ISSUE TITLE
Service Manager API reference in Accelerator Hub changed

### ISSUE THREAD

**Issue by Vector6662** [SAP-docs/btp-service-manager#6]
### Issue description

Service Manager APIs link in this page should be updated, since its url has been changed to https://api.sap.com/api/APIServiceManager/overview, while that original url can't be found now.

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Working with SAP Service Manager APIs

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/service-manager/sap-service-manager/working-with-sap-service-manager-apis?locale=en-US

**Comment by danielforsap** [comment]
Hi,
Thank you for your feedback. The link has already been updated, it will be public after the next release cycle.

**Comment by Vector6662** [comment]
> Thank you for your valuable feedback contribution, @Vector6662! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/dougliu
